<?php
  $session   = Mage::getSingleton( "sveawebpayws/session" );
  $addressId = $session->getSelectedAddressId();
  $addresses = $session->getAddressArray();
  $array = $addresses[ $addressId ];
?>
<?php if( $array != false ): ?>&nbsp;<br />
    
 <?php if(key_exists("FirstName",    $array) && $array["FirstName"]    != "") echo $array["FirstName"].    "<br />"; ?>
 <?php if(key_exists("LastName",     $array) && $array["LastName"]     != "") echo $array["LastName"].     "<br />"; ?>
 <?php if(key_exists("AddressLine2", $array) && $array["AddressLine2"] != "") echo $array["AddressLine2"]. "<br />"; ?>
 <?php if(key_exists("AddressLine1", $array) && $array["AddressLine1"] != "") echo $array["AddressLine1"]. "<br />"; ?>
 <?php if(key_exists("Postcode",     $array) && $array["Postcode"]     != "") echo $array["Postcode"].     "<br />"; ?>
 <?php if(key_exists("Postarea",     $array) && $array["Postarea"]     != "") echo $array["Postarea"].     "<br />"; ?>
  	
<?php endif; ?>