<!-- Text to show when customer gets redirected to SVEA -->
<h1 style="font-style: 25px; margin: 20px 0; text-align: center">
    <?php echo Mage::helper('svea_webpay')->__('redirect'); ?>
</h1>
<p style="text-align: center;"><img src="<?php echo Mage::getBaseUrl("media"); ?>/svea/loader.gif"></p>

<?php $inputFields = $this->getFormHtml(); ?>
<?php echo $inputFields['form_start_tag'] .
        $inputFields['input_merchantId'] .
        $inputFields['input_message'] .
        $inputFields['input_mac'] .
        $inputFields['form_end_tag']; ?>

<script>
$(document).observe('dom:loaded', function(e) {
    $('paymentForm').submit();
});
</script>