<?php

  $session      = Mage::getSingleton( "sveawebpayws/session" );
  $helper       = Mage::helper("sveawebpayws");
  
  $paymentplans = $session->getPaymentplansArray();
  $id           = $session->getSelectedPaymentplanId();
  $option       = $paymentplans[ $id ];
  
  $checkoutSession = Mage::getSingleton("checkout/session");
  $quote = $checkoutSession->getQuote();
  
  $currencyCode = "";
  if($quote)
    $currencyCode = $quote->getQuoteCurrencyCode();
?>

<div class="input-box">
  <span><?php echo $helper->__("InitialFee") ?>:&nbsp;<?php echo $option["InitialFee"]." ".$currencyCode ?></span><br />
  <?php if($option["PaymentPlanType"] != "InterestAndAmortizationFree"): ?>
    <span><?php echo $helper->__("MonthlyAnnuity") ?>:&nbsp;<?php echo $option["MonthlyAnnuity"]." ".$currencyCode ?> </span><br />
  <?php endif; ?>
</div>