<?php
$_code = $this->getMethodCode();
$_content = trim(Mage::getStoreConfig("payment/$_code/redirect_info"));
?>
<?php if (!empty($_content)): ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
        <!-- Show info about payment method entered by admin, if any -->
        <li><?php echo nl2br(Mage::getStoreConfig("payment/$_code/redirect_info")); ?></li>
    </ul>
<?php endif; ?>