<?php

  $_code               = $this->getMethodCode();
  $paymentModel        = $this->getMethod();
  $session             = Mage::getSingleton( "sveawebpayws/session" );
  $helper              = Mage::helper( "sveawebpayws" );
  $counter = 1;
  
  $noCompanyAllowed = $paymentModel->getConfigData("only_private");
  $noCompanyAllowed = ($noCompanyAllowed == 1) ? true : false;
    
  $customer = $paymentModel->getQuote()->getCustomer();
  
  $defaultCountry = $paymentModel->getConfigData("default_country");
  if($defaultCountry === null || !$customer)
    return false;

  $requireEmail = $paymentModel->getConfigData("require_email"); 
  $requireEmail = ($requireEmail == 1) ? true : false;
  
  $email = $customer->getEmail();
  //$phone = $customer->getPhone();
    
  // Hack for finland since we can't do GetAddresses.
  $defaultCountry = Mage::getModel("sveawebpayws/source_defaultcountry")->convertCountryIdToCode( $defaultCountry );
  $isFinnishCountry = ($defaultCountry == "FI");
  
  $subdir = $helper->getSubdirPath();
  
?>

<fieldset class="form-list">
  
  <?php $this->displayImages( $_code ); ?>
  <div id="payment_form_<?php echo $_code ?>" style="display:none;">

    <div class="input-box">
      <label for="<?php echo $_code ?>:security_number" class="required">
        <em>*</em><?php echo $helper->__("LabelSecurityNumber"); ?>
      </label><br />
      
      <input type="text" class="input-text required-entry" id="<?php echo $_code ?>:security_number" name="<?php echo $_code ?>:security_number" /><br />
      
      
    <?php if($noCompanyAllowed): ?>
      <input type="hidden" id="<?php echo $_code ?>:isncmp" value="2" name="<?php echo $_code ?>:isncmp" />
    <?php else: ?>
      <input type="radio" class="input-radio" checked id="<?php echo $_code ?>:isncmp" value="2" name="<?php echo $_code ?>:isncmp" onclick="document.getElementById('<?php echo $_code; ?>:iscmp').checked=false;" />&nbsp;<span><?php echo $helper->__("Pn"); ?></span><br />
      <input type="radio" class="input-radio" id="<?php echo $_code ?>:iscmp" value="1" name="<?php echo $_code ?>:iscmp" onclick="document.getElementById('<?php echo $_code; ?>:isncmp').checked=false;" />&nbsp;<span><?php echo $helper->__("Fn"); ?></span><br />
    <?php endif; ?>
      
      <br />
      
    <?php if(!$isFinnishCountry): ?>
    
      <input type="button" id="submit_button" class="input-button" value="<?php echo $helper->__("AddressButton") ?>"
      	onclick="SWPWSGetAddressesJSON(this,'<?php echo $subdir; ?>','<?php echo $_code ?>','<?php echo $helper->__("AddressInformationDefault") ?>');" />
  		<br /><br />
  		
  		
      <div class="order-info-box" id="<?php echo $_code ?>:address_information_container" style="display:none;">&nbsp;</div>
      <input type="hidden" class="input-hidden required-entry" id="<?php echo $_code ?>:address_hidden_required" />
  
    <?php endif; ?>
    
    <?php
      /* 
      <label for="<?php echo $_code ?>:phone" class="required"><em>*</em><?php echo $helper->__("LabelPhone"); ?></label><br />
      <div class="input-box">
        <input type="text" class="input-text required-entry validate-phoneLax" value="<?php echo $phone; ?>" name="<?php echo $_code ?>:phone" id="<?php echo $_code ?>:phone" />
      </div>
      */
    ?>
    
    <?php if($requireEmail) : ?>
      <label for="<?php echo $_code ?>:email" class="required"><em>*</em><?php echo $helper->__("LabelEmail"); ?></label><br />
      <div class="input-box">
        <input type="text" class="input-text required-entry validate-email" value="<?php echo $email; ?>" name="<?php echo $_code ?>:email" id="<?php echo $_code ?>:email" />
      </div>
    <?php endif; ?>
    
    </div>
  </div>
</fieldset>