<?php
 
  $helper = Mage::helper("sveawebpayws");
  $session = Mage::getSingleton( "sveawebpayws/session" );
  $array   = $session->getAddressArray();
  $counter = 0;
  $useSelectedField = ( count($array) > 1 ) ? true : false;
  $_code = $this->getCode();
   
  $said = $session->getSelectedAddressId();
  if($said > -1)
    $said = 0;
    
  $subdir = $helper->getSubdirPath();
  $selectedArray = Mage::helper("sveawebpayws")->getAddressInformationById( $said );
?>

<?php if($useSelectedField): ?>

  <label><?php echo $helper->__("LabelAddressSelect") ?></label>
  <br />
  
  <select style="width: 100%" id="<?php echo $_code; ?>:select_address" name="<?php echo $_code; ?>:select_address"
      onchange="SWPWSShowAddressJSON('<?php echo $_code ?>','<?php echo $subdir; ?>','aaaa','<?php echo $helper->__("asdasd") ?>');">
      
    <option value="-1">&nbsp;</option>
    
    <?php foreach( $array as $address ) : ?>
    <?php $selected = ($said == $counter) ? "selected" : ""; ?>
    	<option <?php echo $selected ?> value="<?php echo $counter++ ?>">
    	 <?php if($address["AddressLine1"] != "") echo $address["AddressLine1"].","; ?>
    	 <?php if($address["AddressLine2"] != "") echo $address["AddressLine2"]      ?>
      </option>
    <?php endforeach; ?>
    
  </select>
  <br /><br />

<?php  endif; ?>


  
<label><?php echo $helper->__("LabelInvoiceAddress"); ?></label>
<div id="<?php echo $_code; ?>:selected_address_container" style="margin-left: 10px">
<br />
<?php if(!$useSelectedField): ?>

 <?php if(key_exists("FirstName",    $selectedArray) && $selectedArray["FirstName"] != "") echo $selectedArray["FirstName"].    "<br />"; ?>
 <?php if(key_exists("LastName",     $selectedArray) && $selectedArray["LastName"] != "") echo $selectedArray["LastName"].     "<br />"; ?>
 <?php if(key_exists("AddressLine2", $selectedArray) && $selectedArray["AddressLine2"] != "") echo $selectedArray["AddressLine2"]. "<br />"; ?>
 <?php if(key_exists("AddressLine1", $selectedArray) && $selectedArray["AddressLine1"] != "") echo $selectedArray["AddressLine1"]. "<br />"; ?>
 <?php if(key_exists("Postcode",     $selectedArray) && $selectedArray["Postcode"] != "") echo $selectedArray["Postcode"].     "<br />"; ?>
 <?php if(key_exists("Postarea",     $selectedArray) && $selectedArray["Postarea"] != "") echo $selectedArray["Postarea"].     "<br />"; ?>
 
<?php else: ?>


<?php echo $helper->__("SelectAddressFromListAbove"); ?>
<input type="hidden" class="input-hidden required-entry" />
<?php endif; ?>


</div>