<?php
$_code = $this->getMethodCode();
$_infoBlock = trim(Mage::getStoreConfig("payment/$_code/paymentplan_info"));
$_ssnHtml = $this->getSsnHtml();
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>"
    style="display:none;">
    <?php if (!empty($_infoBlock)): ?>
    <li>
        <?php echo(nl2br($_infoBlock)); ?>
    </li>
    <?php endif ?>

    <?php if (!empty($_ssnHtml)): ?>
        <li>
            <?php echo $_ssnHtml ?>
        </li>
    <?php endif ?>
</ul>