<?php
$_country = Mage::getSingleton('checkout/session')
    ->getQuote()
    ->getBillingAddress()
    ->getCountry();

$_code = $this->getMethodCode();
$_lang = strtoupper(Mage::helper('svea_webpay')->__('lang_code'));
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>"
    style="display:none;">
    <li>
        <label for=""></label>
        <?php echo(nl2br(Mage::getStoreConfig("payment/$_code/invoice_info"))); ?>
    </li>
    <li>
        <label
            for="svea_customerType"><?php echo Mage::helper('svea_webpay')->__('customer_type') . ":"; ?></label>

        <div class="input-box">
            <input type="radio"
                   id="payment_form_<?php echo $_code ?>_customerType_0"
                   name="payment[<?php echo $_code ?>_customerType]" value="0"
                   checked> <?php echo Mage::helper('svea_webpay')->__('private'); ?>
            <input type="radio"
                   id="payment_form_<?php echo $_code ?>_customerType_1"
                   name="payment[<?php echo $_code ?>_customerType]"
                   value="1"> <?php echo Mage::helper('svea_webpay')->__('company'); ?>
            <!--
            <select class="" id="payment_form_<?php echo $_code ?>_customerType" name="payment[<?php echo $_code ?>_customerType]">
                <option value="0"><?php echo Mage::helper('svea_webpay')->__('private'); ?></option>
                <option value="1"><?php echo Mage::helper('svea_webpay')->__('company'); ?></option>
            </select>
            -->
        </div>
    </li>

    <!-- If Nordic countries show, show SSN input field -->
    <?php if (in_array($_country, array('SE', 'DK', 'NO', 'FI'))): ?>
        <li>
            <label for="payment_form_<?php echo $_code ?>_ssn" class="required"
                   id="label_<?php echo $_code ?>_ssn_customerType_0"><em>*</em><?php echo Mage::helper('svea_webpay')->__('text_ssn') . ":"; ?>
            </label>
            <label style="display:none;"
                   for="payment_form_<?php echo $_code ?>_ssn" class="required"
                   id="label_<?php echo $_code ?>_ssn_customerType_1"><em>*</em><?php echo Mage::helper('svea_webpay')->__('text_vat_no') . ":"; ?>
            </label>

            <div class="input-box">
                <input type="text" title="payment_form_<?php echo $_code ?>_ssn"
                       class="input-text required-entry"
                       id="payment_form_<?php echo $_code ?>_ssn"
                       name="payment[<?php echo $_code ?>_ssn]"/>
            </div>
        </li>
    <?php endif; ?>

    <!-- If DE or NL, show dropdowns for birth date -->
    <?php if (in_array($_country, array('NL', 'DE'))): ?>
        <li class="forNLDE">
            <label for="payment_form_<?php echo $_code ?>_birthYear"
                   class="required"><em>*</em><?php echo Mage::helper('svea_webpay')->__('text_birthyear') . ":"; ?>
            </label>

            <div class="input-box">
                <select id="payment_form_<?php echo $_code ?>_birthYear"
                        name="payment[<?php echo $_code ?>_birthYear]"
                        class="required validate-select">
                    <option
                        value=""><?php echo $this->__('-- Select --') ?></option>
                    <?php $_currentYear = date('Y'); ?>
                    <?php for ($_year = $_currentYear - 100; $_year <= $_currentYear - 17; $_year++): ?>
                        <option
                            value="<?php echo $_year ?>"><?php printf("%04d", $_year) ?></option>
                    <?php endfor ?>
                </select>
            </div>
        </li>
        <li class="forNLDE">
            <label for="payment_form_<?php echo $_code ?>_birthMonth"
                   class="required"><em>*</em><?php echo Mage::helper('svea_webpay')->__('text_birthmonth') . ":"; ?>
            </label>

            <div class="input-box">
                <select id="payment_form_<?php echo $_code ?>_birthMonth"
                        name="payment[<?php echo $_code ?>_birthMonth]"
                        class="required validate-select">
                    <option
                        value=""><?php echo $this->__('-- Select --') ?></option>
                    <?php for ($_month = 1; $_month <= 12; $_month++): ?>
                        <option
                            value="<?php echo $_month ?>"><?php printf("%02d", $_month) ?></option>
                    <?php endfor ?>
                </select>
            </div>
        </li>
        <li class="forNLDE">
            <label for="payment_form_<?php echo $_code ?>_birthDay"
                   class="required"><em>*</em><?php echo Mage::helper('svea_webpay')->__('text_birthday') . ":"; ?>
            </label>

            <div class="input-box">
                <select id="payment_form_<?php echo $_code ?>_birthDay"
                        name="payment[<?php echo $_code ?>_birthDay]"
                        class="required validate-select">
                    <option
                        value=""><?php echo $this->__('-- Select --') ?></option>
                    <?php for ($_day = 1; $_day <= 31; $_day++): ?>
                        <option
                            value="<?php echo $_day ?>"><?php printf("%02d", $_day) ?></option>
                    <?php endfor ?>
                </select>
            </div>
        </li>
    <?php endif; ?>

    <!-- If NL, DE or FI show VAT no input -->
    <?php if (in_array($_country, array('NL', 'DE', 'FI'))): ?>
        <li id="forNLDEcompany" style="display:none;">
            <label for="payment_form_<?php echo $_code ?>_vatNo"
                   class="required"><em>*</em><?php echo Mage::helper('svea_webpay')->__('text_vat_no') . ":"; ?>
            </label>

            <div class="input-box">
                <input type="text"
                       title="payment_form_<?php echo $_code ?>_vatNo"
                       class="input-text required-entry"
                       id="payment_form<?php echo $_code ?>_vatNo"
                       name="payment[<?php echo $_code ?>_vatNo]"/>
            </div>
        </li>
    <?php endif; ?>

    <!-- If NL show input field for initials -->
    <?php if ($_country == "NL"): ?>
        <li class="forNLDE forNL">
            <label for="payment_form_<?php echo $_code ?>_initials"
                   class="required"><em>*</em><?php echo Mage::helper('svea_webpay')->__('text_initials') . ":"; ?>
            </label>

            <div class="input-box">
                <input type="text"
                       title="payment_form_<?php echo $_code ?>_initials"
                       class="input-text required-entry"
                       id="payment_form_<?php echo $_code ?>_initials"
                       name="payment[<?php echo $_code ?>_initials]"/>
            </div>
        </li>
    <?php endif; ?>

    <li>&nbsp;</li>

    <!-- Hide get address button for FI, NL, NO and DE -->
    <?php if (in_array($_country, array('SE', 'DK'))): ?>
        <li id="showInvoiceAddressBox">
            <label
                for="sveaInvoiceShowAddressest"><?php echo Mage::helper('svea_webpay')->__('invoice_address') . ":"; ?></label>

            <div id="sveaInvoiceShowAddresses"
                 style="display:inline-block;"></div>
        </li>
        <li>
            <div id="payment-method-buttons-container" class="buttons-set">
                <button class="button" id="getAddress"
                        onclick="sveaGetAddress();" type="button">
                    <span><span><?php echo Mage::helper('svea_webpay')->__('get_address'); ?></span></span>
                </button>
            </div>
        </li>
    <?php endif; ?>
</ul>

<script>

    var currentCountry = <?php echo Mage::helper('core')->jsonEncode($_country) ?>;
    $("payment_form_<?php echo $_code ?>_customerType_0").observe("change", function (e) {
        customerType = $(this).value;
        if (currentCountry == 'NL' || currentCountry == 'DE') {
            if ($(this).value == 1) {
                $$(".forNLDE").each(function (element) {
                    $(element).hide();
                });
                $("forNLDEcompany").show();
            } else {
                $("forNLDEcompany").hide();
                $$(".forNLDE").each(function (element) {
                    $(element).show();
                });
            }
        } else {
            if ($(this).value == 1) {
                $("label_<?php echo $_code ?>_ssn_customerType_0").hide();
                $("label_<?php echo $_code ?>_ssn_customerType_1").show();
            } else {
                $("label_<?php echo $_code ?>_ssn_customerType_1").hide();
                $("label_<?php echo $_code ?>_ssn_customerType_0").show();
            }

        }
    });
    $("payment_form_<?php echo $_code ?>_customerType_1").observe("change", function (e) {
        customerType = $(this).value;
        if (currentCountry == 'NL' || currentCountry == 'DE') {
            if ($(this).value == 1) {
                $$(".forNLDE").each(function (element) {
                    $(element).hide();
                });
                $("forNLDEcompany").show();
            } else {
                $("forNLDEcompany").hide();
                $$(".forNLDE").each(function (element) {
                    $(element).show();
                });
            }
        } else {
            if ($(this).value == 1) {
                $("label_<?php echo $_code ?>_ssn_customerType_0").hide();
                $("label_<?php echo $_code ?>_ssn_customerType_1").show();
            } else {
                $("label_<?php echo $_code ?>_ssn_customerType_1").hide();
                $("label_<?php echo $_code ?>_ssn_customerType_0").show();
            }

        }
    });

    window.sveaGetAddress = function (e) {
        // Set vars
        var ssn = $("payment_form_<?php echo $_code ?>_ssn").value;
        var loader = "<img src='<?php echo Mage::getBaseUrl("media", true); ?>svea/loader.gif' id='sveaLoader'>";
        var type = $$('input:checked[type=radio][name*=payment[svea_invoice_customerType]]')[0].value;

        // Show Loader
        $("sveaInvoiceShowAddresses").update().insert(loader);

        new Ajax.Request('<?php echo $this->getUrl('svea_webpay/service/getAddresses', array('_secure' => true)) ?>', {
            parameters: {ssn: ssn, type: type, cc: "<?php echo $_country; ?>"},
            onSuccess: function (transport) {
                var json = transport.responseText.evalJSON();
                $("sveaLoader").remove();

                if (json.accepted == false) {
                    $("sveaInvoiceShowAddresses").update("<span style='color:red'>" + json.errormessage + "</span>");
                    return;
                }

                var addressElement = $('<?php echo $_code ?>_addressSelector');
                if (addressElement) {
                    $(addressElement).remove();
                }

                // Show dropdown if company, show only text if private customer
                if (json.customerIdentity.length > 1) {
                    var selectBox = "<select id='<?php echo $_code ?>_addressSelector' name='payment[<?php echo $_code ?>_addressSelector]'>";

                    json.customerIdentity.each(function (item) {
                        selectBox += "<option value='" + item.addressSelector + "'>" + item.fullName + ", " + item.street + ", " + item.zipCode + " " + item.locality;
                        +"</option>";
                    });

                    selectBox += "</select>";

                    $("sveaInvoiceShowAddresses").insert(selectBox);
                } else {
                    $("sveaInvoiceShowAddresses").insert(new Element('input', {
                        type: 'hidden',
                        'id': '<?php echo $_code ?>_addressSelector',
                        'name': 'payment[<?php echo $_code ?>_addressSelector]',
                        'value': json.customerIdentity[0].addressSelector
                    }));

                    if (json.customerIdentity[0].fullName == null) {
                        var name = json.customerIdentity[0].firstName + " " +
                            json.customerIdentity[0].lastName + "<br>";
                    } else {
                        var name = json.customerIdentity[0].fullName + "<br>";
                    }
                    var adress = name +
                        json.customerIdentity[0].street + "<br>" +
                        json.customerIdentity[0].zipCode + " " +
                        json.customerIdentity[0].locality;

                    $("sveaInvoiceShowAddresses").insert(adress)

                    //For onestep checkouts, check if fields visible and auto-fill
                    if ($("billing:firstname").visible()) {
                        $("billing:firstname").value = json.customerIdentity[0].firstName;
                        $("billing:lastname").value = json.customerIdentity[0].lastName;
                        $("billing:street1").value = json.customerIdentity[0].street;
                        $("billing:city").value = json.customerIdentity[0].locality;
                        $("billing:postcode").value = json.customerIdentity[0].zipCode;
                    }
                }
            }
        });
    }
</script>
