<?php
// This key will be used in forms if there is only one set of inputs for svea
$_unifiedInterfaceFormKey = 'svea_info';

// If no method is set it's assumed that the frontend uses a single set of inputs
// for all svea payment methods. The key which these inputs will use will then be
// $_unifiedInterfaceFormKey
$_method = $this->getMethod();
$_useUnifiedGui = empty($_method);

if ($_useUnifiedGui) {
    $_formKey = $_unifiedInterfaceFormKey;
} else {
    $_formKey = $_method->getCode();
}

$_helper = Mage::helper('svea_webpay');

$_currency = Mage::app()->getStore()->getCurrentCurrencyCode();
$_code = $this->getMethodCode();

$_infoHtml = $this->getInfoHtml();
$_resultParams = $this->getPaymentPlans();
$_ssnHtml = $this->getSsnHtml();

?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <?php if (!empty($_infoHtml)): ?>
        <li>
            <?php echo $_infoHtml; ?>
        </li>
    <?php endif; ?>

    <!-- Show stored payment plan params -->
    <li id="showPaymentPlanParams">
        <div id="sveaPaymentPlanShowParams" style="display:inline-block;">
            <select onchange="_updatePaymentPlanPrice();"
                    id="paymentplan_campaign_chooser" name="payment[<?php echo $_formKey ?>][campaign]">
                <?php
                $_i = 0;
                $_campaigns = array();
                foreach ($_resultParams as $_campaign): $_i++;
                    ?>
                    <?php $_selected = ($_i === 1) ? "selected" : "" ?>
                    <?php if ($_campaign['isCampaign']): ?>
                        <option <?php echo $_selected ?>
                            value="<?php echo $_campaign['campaignCode']; ?>"> <?php echo $_campaign['description']; ?></option>
                    <?php else: ?>
                        <option <?php echo $_selected ?>
                            value="<?php echo $_campaign['campaignCode'] ?>"> <?php echo $_campaign['paymentPlan']->contractlength; ?>
                            mån
                        </option>
                    <?php endif; ?>
                    <?php
                    $_campaigns[] = array(
                        'code' => $_campaign['campaignCode'],
                        'amount' => $_campaign['pricePerMonth'],
                        'notification_fee' => $_campaign['notificationFee'],
                        'is_campaign' => $_campaign['isCampaign'],
                        'initial_fee' => $_campaign['initialFee'],
                    );

                endforeach;
                ?>
            </select>
            <br>

            <div class="paymentplan_info" id="paymentplan_info" style="display:none">
                <p id="paymentplan_cost_text" style="display:none">
                    <?php echo $_helper->__('Your monthly cost') ?>: <span class="cost"><span id="paymentplan_cost"></span> <?php echo $_currency . "/" . $_helper->__('month') ?></span>
                </p>

                <p id="paymentplan_initial_fee_text" style="display:none">
                    <?php echo Mage::helper('svea_webpay')->__('initial_fee') ?>: <span></span> <?php echo $_currency ?>
                </p>
            </div>
        </div>
    </li>

    <?php if (!empty($_ssnHtml)): ?>
        <li>
            <?php echo $_ssnHtml ?>
        </li>
    <?php endif ?>
</ul>

<script>
    var available_campaigns = <?php echo Mage::helper('core')->jsonEncode($_campaigns) ?>;
    function _updatePaymentPlanPrice() {
        var selectedOption = $$('#paymentplan_campaign_chooser option').find(function (el) {
            return !!el.selected;
        });

        for (var i = 0; i < available_campaigns.length; i++) {
            if (available_campaigns[i].code == selectedOption.value) {
                if (available_campaigns[i].is_campaign) {
                    $('paymentplan_cost_text').hide();
                } else {
                    $('paymentplan_cost_text').show();
                    $('paymentplan_cost').update(available_campaigns[i].amount);
                }
                $('paymentplan_initial_fee_text').down('span').update(available_campaigns[i].initial_fee);

                // Convert to int here to check if there is an initial fee.
                // If 0 < initial_fee < 0.49 this is a bug.
                if (parseFloat(available_campaigns[i].initial_fee) !== 0) {
                    $('paymentplan_initial_fee_text').show();
                } else {
                    $('paymentplan_initial_fee_text').hide();
                }

                if (!$('paymentplan_cost_text').visible()
                    && !$('paymentplan_initial_fee_text').visible()) {
                    $('paymentplan_info').hide();
                } else {
                    $('paymentplan_info').show();
                }
            }
        }
    }

    window._updatePaymentPlanPrice = _updatePaymentPlanPrice;
    _updatePaymentPlanPrice();
</script>
