<?php
$_country = Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress()->getCountry();
$_currency = Mage::app()->getStore()->getCurrentCurrencyCode();
$_code = $this->getMethodCode();
$_lang = strtoupper(Mage::helper('svea_webpay')->__('lang_code'));

$_resultParams = Mage::helper('svea_webpay')->getPaymentPlanParams();
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>"
    style="display:none;">
    <li>
        <?php echo(nl2br(Mage::getStoreConfig("payment/$_code/paymentplan_info"))); ?>
    </li>

    <?php echo $this->getSsnHtml() ?>

    <!-- Show stored payment plan params -->
    <li id="showPaymentPlanParams">
        <div id="sveaPaymentPlanShowParams" style="display:inline-block;">
            <?php $_i = 0;
            foreach ($_resultParams as $_campaign): $_i++; ?>
                <?php $_selected = ($_i === 1) ? "checked='checked'" : "" ?>
                <label>
                    <input type="radio"
                           name="payment[<?php echo $_code ?>_campaign]" <?php echo $_selected ?>
                           value="<?php echo $_campaign->campaincode; ?>"> <?php echo $_campaign->description; ?>
                    - <?php echo $_campaign->monthlyamount . " " . $_currency . "/" . Mage::helper('svea_webpay')->__('month') ?>
                </label>
                <br>
            <?php endforeach ?>
        </div>
    </li>
</ul>