<?php

if (!$this->shouldRenderTemplate()) {
    return;
}

$_code = $this->getFrontendId();

// Add class regardless of unified interface or not
$_class = 'svea-ssn-container-' . $_code;

$_useCustomerTypeSelector = in_array($_code, array('svea_invoice', 'svea_info'));

// Get country for later
$_country = Mage::getSingleton('checkout/session')
    ->getQuote()
    ->getBillingAddress()
    ->getCountry();

$_sveaHelper = Mage::helper('svea_webpay');

?>

<div class="svea-ssn-container <?php echo $_class ?>">
    <?php
    /** The hidden input below is used to find out country in checkouts that
     * doesn't display billing:country_id or payment_method, like the magento
     * old checkout (not onepage).
     *
     * See _sveaGetBillingCountryCode() in svea.js.
     */
    ?>
    <input type="hidden" id="svea-billing-country-id-<?php echo $_code; ?>" disabled name="svea-billing-country-id" value="<?php echo $_country; ?>">

    <?php if ($_useCustomerTypeSelector): ?>
        <?php
         /**
            These radios are not the real values sent to the server because some
            checkout sollutions doesn't handle radios very well. They will notify
            the SVEA controller by firing an event on <body>.
         */
        ?>
        <div class="field">
            <label style="margin-right: 30px;">
                <input type="radio"
                       class="payment_form_customerType_0"
                       name="_svea_customerType"
                       value="0"
                       onclick="(function(){$$('body')[0].fire('svea:customerTypeChanged',$(this).value);}).call(this);"
                       checked> <?php echo $_sveaHelper->__('private'); ?>
            </label>
            <label>
                <input type="radio"
                       class="payment_form_customerType_1"
                       name="_svea_customerType"
                       onclick="(function(){$$('body')[0].fire('svea:customerTypeChanged',$(this).value);}).call(this);"
                       value="1"> <?php echo $_sveaHelper->__('company'); ?>
            </label>
        </div>
    <?php endif ?>

    <?php /* This is always used, if radios are used they will have to copy their current value to this input */ ?>
    <input type="hidden" name="payment[<?php echo $_code ?>][svea_customerType]" value="0">

    <!-- If Nordic countries show, show SSN input field -->
    <?php if (in_array($_country, array('SE', 'DK', 'NO', 'FI'))): ?>
        <div class="field <?php if (in_array($_country, array('SE', 'DK'))): ?>float-btn<?php endif;?>">
            <label class="required" for="payment_form_ssn_<?php echo $_code ?>">
                <em>*</em>
                <span class="label_ssn_customerType_0"><?php echo $_sveaHelper->__('text_ssn') ?></span>
                <span class="label_ssn_customerType_1" style="display:none;"><?php echo $_sveaHelper->__('text_vat_no') ?></span>
            </label>

            <div class="input-box">
                <input type="text"
                       id="payment_form_ssn_<?php echo $_code ?>"
                       class="svea-ssn-input validate-svea-invoice-ssn input-text required-entry"
                       name="payment[<?php echo $_code ?>][svea_ssn]"/>
            </div>

            <!-- Hide get address button for FI, NL, NO and DE -->
            <?php if (in_array($_country, array('SE', 'DK'))): ?>
                <div id="payment-method-buttons-container-<?php echo $_code ?>" class="field get-address-btn">
                    <button class="button"
                            onclick="(function(){$$('body')[0].fire('svea:getAddressFromServer');})();"
                            type="button">
                        <span>
                            <span class="inner"><?php echo $_sveaHelper->__('get_address'); ?></span>
                            <span class="loader"><img src="<?php echo $this->getSkinUrl('svea/images/ajax-loader-white.gif') ?>"></span>
                        </span>

                    </button>

                </div>
            <?php endif; ?>
            
            <?php if ($_sveaHelper->createOrderOverwritesAddressForCountry($_country)): ?>
                <div class="address-disclaimer"><?php echo $this->__('The Invoice will be sent to the address registered to your social security number'); ?></div>
            <?php endif ?>
            
        </div>

        <!-- hidden public key input -->
        <input type="hidden" name="svea_publicKey">

        <!-- Hide address select box for FI, NL, NO and DE -->
        <?php if (in_array($_country, array('SE', 'DK'))): ?>
            <select class="svea_address_selectbox" onchange="sveaAddressSelectChanged.call(this);"
                    style="display:none;margin-top:8px;width:100%"></select>
            <?php
            ?>

            <?php if ($_sveaHelper->showSsnSelectorInPaymentMethod()): ?>
                <div id="showAddressBox_<?php echo $_code ?>" class="field">
                    <label class="sveaShowAdressesLabel" for="sveaShowAddresses_<?php echo $_code ?>" style="display:none"><?php echo $_sveaHelper->__('invoice_address'); ?></label>

                    <div class="sveaShowAddresses"
                         id="sveaShowAddresses_<?php echo $_code ?>"></div>
                </div>
            <?php endif ?>

        <?php endif; ?>
    <?php endif; ?>

    <!-- If DE or NL, show dropdowns for birth date -->
    <?php if (in_array($_country, array('NL', 'DE'))): ?>
        <div class="field forNLDE">
            <label for="payment_form_birthYear_<?php echo $_code ?>"
                   class="required"><em>*</em><?php echo $_sveaHelper->__('text_birthyear'); ?>
            </label>

            <div class="input-box">
                <select id="payment_form_birthYear_<?php echo $_code ?>"
                        name="payment[<?php echo $_code ?>][svea_birthYear]"
                        class="required validate-select">
                    <option
                        value=""><?php echo $this->__('-- Select --') ?></option>
                    <?php $_currentYear = date('Y'); ?>
                    <?php for ($_year = $_currentYear - 100; $_year <= $_currentYear - 17; $_year++): ?>
                        <option
                            value="<?php echo $_year ?>"><?php printf("%04d", $_year) ?></option>
                    <?php endfor ?>
                </select>
            </div>
        </div>
        <div class="field forNLDE">
            <label for="payment_form_birthMonth_<?php echo $_code ?>"
                   class="required"><em>*</em><?php echo $_sveaHelper->__('text_birthmonth'); ?>
            </label>

            <div class="input-box">
                <select id="payment_form_birthMonth_<?php echo $_code ?>"
                        name="payment[<?php echo $_code ?>][svea_birthMonth]"
                        class="required validate-select">
                    <option
                        value=""><?php echo $this->__('-- Select --') ?></option>
                    <?php for ($_month = 1; $_month <= 12; $_month++): ?>
                        <option
                            value="<?php echo $_month ?>"><?php printf("%02d", $_month) ?></option>
                    <?php endfor ?>
                </select>
            </div>
        </div>
        <div class="field forNLDE">
            <label for="payment_form_birthDay_<?php echo $_code ?>"
                   class="required"><em>*</em><?php echo $_sveaHelper->__('text_birthday'); ?>
            </label>

            <div class="input-box">
                <select id="payment_form_birthDay_<?php echo $_code ?>"
                        name="payment[<?php echo $_code ?>][svea_birthDay]"
                        class="required validate-select">
                    <option
                        value=""><?php echo $this->__('-- Select --') ?></option>
                    <?php for ($_day = 1; $_day <= 31; $_day++): ?>
                        <option
                            value="<?php echo $_day ?>"><?php printf("%02d", $_day) ?></option>
                    <?php endfor ?>
                </select>
            </div>
        </div>
    <?php endif; ?>

    <!-- If NL, DE or FI show VAT no input -->
    <?php if (in_array($_country, array('NL', 'DE', 'FI'))): ?>
        <div class="field forNLDEcompany" style="display:none;">
            <label for="payment_form_vatNo_<?php echo $_code ?>"
                   class="required"><em>*</em><?php echo $_sveaHelper->__('text_vat_no'); ?>
            </label>

            <div class="input-box">
                <input type="text"
                       title="payment_form_vatNo"
                       class="input-text required-entry"
                       id="payment_form_vatNo_<?php echo $_code ?>"
                       name="payment[<?php echo $_code ?>][svea_vatNo]"/>
            </div>
        </div>
    <?php endif; ?>

    <!-- If NL show input field for initials -->
    <?php if ($_country == "NL"): ?>
        <div class="field forNLDE forNL">
            <label for="payment_form_initials_<?php echo $_code ?>"
                   class="required"><em>*</em><?php echo $_sveaHelper->__('text_initials'); ?>
            </label>

            <div class="input-box">
                <input type="text"
                       title="payment_form_initials"
                       class="input-text required-entry"
                       id="payment_form_initials_<?php echo $_code ?>"
                       name="payment[<?php echo $_code ?>][svea_initials]"/>
            </div>
        </div>
    <?php endif; ?>

    <input type="hidden" name="payment[<?php echo $_code ?>][svea_addressSelector]" class="svea_address_selector">
    <input type="hidden" name="payment[<?php echo $_code ?>][svea_publicKey]">
</div>

<script>
    // This html is loaded by ajax some times, so only overwrite window._svea if it
    // isn't set
    if (!window._svea) {
        window._svea = {};
    }

    window._svea.useFormKey = <?php echo $_code === 'svea_info' ? 'true' : 'false' ?>;
    window._svea.formKey = <?php echo $_code === 'svea_info' ? "'$_code'" : 'null' ?>;
    window._svea.lockRequiredFields = <?php echo $this->shouldLockRequiredFields() ? 'true': 'false' ?>;
    window._svea.alwaysDisplaySsnSelector = <?php echo json_encode($_sveaHelper->alwaysDisplaySsnSelector()); ?>;

    // Create svea controller if the controller doesn't exist
    if (!window._svea.controller) {
        var config = {};
        config.getAddressUrl = '<?php echo $this->getUrl('svea_webpay/service/getAddresses', array('_secure' => true)) ?>';
        config.useGetAddressForAllPaymentMethods = <?php echo $_sveaHelper->alwaysDisplaySsnSelector() ? 'true': 'false'; ?>;
        config.oneStepCheckoutSetMethodsSeparateUrl = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        window._svea.controller = new _SveaController(config);
    }
</script>
