<?php
if ($this->displayBoth()):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() . ' ('  . Mage::helper('tax')->getIncExcText(false) . ')' ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueExcl()) ?>
    </td>
</tr>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() . ' ('  . Mage::helper('tax')->getIncExcText(true) . ')'?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueIncl()) ?>
    </td>
</tr>
<?php else : ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <?php $value = $this->displayIncl() ? $this->getTotal()->getValueIncl() : $this->getTotal()->getValueExcl() ?>
        <?php echo $this->helper('checkout')->formatPrice($value) ?>
    </td>
</tr>
<?php endif;?>