<?php
$_priceWidget = $this->getPricewidgetData();
?>

<?php if ($this->isProductPage() && $_priceWidget['enabled']): ?>
<div class="sveaCampainInfo">

    <span><?php echo $_priceWidget['label'] ?></span>

    <ul class="dropdown"><?php foreach ($_priceWidget['methods'] as $_method): ?>
        <li>
            <ul><?php echo $_method['label'] ?>
                <?php foreach ($_method['rows'] as $row): ?>
                <li>
                    <span class="label"><?php echo $row['label'] ?></span>
                    <span class="cost"><?php echo $row['cost'] ?></span>
                </li>
                <?php endforeach ?>
            </ul>
        </li>
        <?php endforeach ?>
    </ul>

</div>
<?php endif ?>
