<!-- Show the least cost per month sentence -->
<?php
$_lang = strtoupper(Mage::helper('svea_webpay')->__('lang_code'));
?>

<div class="sveaCampainInfo">
    <?php if ($this->isProductPage()): ?>
        <!-- Display extended campaign info -->
        <?php foreach ($this->getCampaigns() as $campaign): ?>
            <?php // Print single campaign info here ?>
            <?php // echo $this->getCampaignString($campaign) ?>
        <?php endforeach ?>
        
        <?php echo $this->getCampaignString($this->getCheapestCampaign()) ?>
    <?php else: ?>
        <?php echo $this->getCampaignString($this->getCheapestCampaign()) ?>
    <?php endif ?>
    <p>
        <img src="<?php echo Mage::getBaseUrl("media"); ?>svea/<?php echo $_lang?>/svea_paymentplan.png">
    </p>
</div>